### ISSUE TITLE
[error] Throws an error without specifying task name 

### ISSUE THREAD

**Issue by w20k** [leecrossley/grunt-timer#9]
While executing grunt in console without specifying tasks name, it throws an error. As a proposal, should have an option to skip default task. 

Could be this way.

```
module.exports = function (grunt) {
            timer.init(grunt, {default: false});
```

In my case, I want to use default task as a help options. When I type grunt in console, it will show me the list of available tasks.

in console typing: grunt

Grunt output:

```
Done, without errors.

TypeError: undefined is not a Date object
    at module.exports (C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt-timer\node_modules\duration\node_modules\es5-ext\date\valid-date.js:6:24)
    at Object.module.exports (C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt-timer\node_modules\duration\index.js:47:14)
    at module.exports.logCurrent (C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt-timer\grunt-timer.js:29:19)
    at process.<anonymous> (C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt-timer\grunt-timer.js:105:13)
    at process.EventEmitter.emit (events.js:117:20)
    at process.exit (node.js:707:17)
    at tryToExit (C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt\node_modules\exit\lib\exit.js:17:15)
    at Object.exit (C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt\node_modules\exit\lib\exit.js:34:3)
    at Object.task.options.done (C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt\lib\grunt.js:154:14)
    at Task.<anonymous> (C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt\lib\util\task.js:280:25)
    at C:\Users\denis.denisov\Desktop\project\ember-grunt-browserify\node_modules\grunt\lib\util\task.js:227:11
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3
```

Gruntfile.coffee -> grunt config

```
#gruntjs

module.exports = (grunt) ->
  'use strict'

  require('matchdep').filterDev('grunt-*').forEach(grunt.loadNpmTasks)
 require('grunt-timer').init(grunt, {deferLogs: true, friendlyTime: true})

  grunt.initConfig(
    options:
      port: 3000
      path:
        client: 'client'
        server: 'server'
        bower: 'client/bower_components'
        dist:
          client: 'dist/client'
          server: 'dist/server'
        tmp:
          client: '.tmp/client'
          server: '.tmp/server'

    availabletasks:
      options:
        filter: 'include'
        tasks: ['bower']

    bower:
      install:
        targetDir: '<% options.path.bower %>'

 )

  grunt.registerTask 'default', 'availabletasks'
```
